version: '3.8'

name: manuel90_github_io

services:
  nodejs:
    container_name: manuel90_github_io_nodejs
    build:
      context: .
      args:
        - NODE_VERSION=22.11.0
    volumes:
      - './:/home/app'
    ports:
      - "3001:3000"
    networks:
      - manuel90_github_io_net
networks:
  manuel90_github_io_net:
    name: manuel90_github_io_net_name
    driver: bridge
    
